# Site settings
title: Open Lab, Newcastle Universityでの在外研究
email: matsumur@acm.org
description: > # this means to ignore newlines until "baseurl:"
  在外研究の記録と記憶
baseurl: "/ncl" # the subpath of your site, e.g. /blog/
url: "https://matsumur.github.io/ncl" # the base hostname & protocol for your site
logo: "openlab.jpg"


owner:
  name:           Kohei Matsumura
  avatar:         na.jpg
  email:          matsumur@acm.org
  description:    An assistant proffessor at Ritsumeikan University, Japan.
  twitter:        matsumur
  facebook:       matsumur

# Build settings
markdown: kramdown

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

- jekyll-feed

links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Featured Posts
    url: /featured
  - title: Categories
    url: /categories
  - title: About
    url: /about
    